sudo: false
language: node_js
node_js:
  - '8'
  - '10'
  - '12'
jdk: oraclejdk8
before_install:
  - echo $JAVA_HOME
  - java -version
  - 'wget https://github.com/alibaba/nacos/releases/download/1.0.0/nacos-server-1.0.0.tar.gz'
  - 'wget https://github.com/gxcsoccer/PDisk/releases/download/1.0.1/startup.sh'
  - 'tar xf nacos-server-1.0.0.tar.gz'
  - 'mv ./startup.sh ./nacos/bin/startup.sh'
  - 'chmod 755 ./nacos/bin/startup.sh'
  - 'nohup ./nacos/bin/startup.sh -m standalone 2>&1 &'
  - 'sleep 30'
  - 'cat nohup.out'
  - 'curl "127.0.0.1:8848/nacos/v1/ns/operator/metrics"'
install:
  - npm i npminstall && npminstall
  - npm run bootstrap
  - npm run build
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
